# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LayerFromClipboard
                                 A QGIS plugin
 create layer from clipboard data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-04-29
        copyright            : (C) 2018 by Jorge Almaraz
        email                : jalmmor@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LayerFromClipboard class from file LayerFromClipboard.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .layer_from_clipboard import LayerFromClipboard
    return LayerFromClipboard(iface)
